-- Demo-only. Backs the Development Status tab -- lets status/notes edits made
-- in the UI persist across restarts instead of resetting to a bundled default
-- every time. Applied only under the "demo" Spring profile, same as V3.

CREATE TABLE dev_status_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category    VARCHAR(64) NOT NULL,
    item        VARCHAR(512) NOT NULL,
    status      VARCHAR(1) NOT NULL CHECK (status IN ('N', 'P', 'C')),
    notes       VARCHAR(1024),
    updated_at  TIMESTAMP WITH TIME ZONE
);
