-- Ported from app/demo/consumer_store.py (ConsumerAccount / consumer_customer_accounts).
-- Demo-only: models the *other half* of the architecture -- this HSM service never
-- stores ciphertext itself; a calling app (simulated here as payments-svc) owns its
-- own schema and stores the opaque ciphertext_token next to its own non-sensitive
-- columns. Applied only under the "demo" Spring profile (see application-demo.yml's
-- extra spring.flyway.locations entry) -- not part of the production schema.

CREATE TABLE consumer_customer_accounts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_name     VARCHAR(128) NOT NULL,
    email             VARCHAR(256) NOT NULL,
    ciphertext_token  VARCHAR(512) NOT NULL,
    created_at        TIMESTAMP WITH TIME ZONE
);
