apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hsm.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hsm.labels" . | nindent 4 }}
data:
  DEMO_MODE: {{ .Values.config.demoMode | quote }}
  SKIP_AKV: {{ .Values.config.skipAkv | quote }}
  SERVICE_ENV: {{ .Values.config.serviceEnv | quote }}
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  API_V1_PREFIX: {{ .Values.config.apiV1Prefix | quote }}
  DEK_BATCH_MAX_ITEMS: {{ .Values.config.dekBatchMaxItems | quote }}

  NAMED_DEK_ROTATION_CRON: {{ .Values.config.namedDekRotationCron | quote }}
  NAMED_DEK_ROTATION_ENABLED: {{ .Values.config.namedDekRotationEnabled | quote }}
  NAMED_DEK_ROTATION_MAX_AGE_HOURS: {{ .Values.config.namedDekRotationMaxAgeHours | quote }}

  AZURE_CLIENT_ID: {{ .Values.config.azureClientId | quote }}
  AZURE_TENANT_ID: {{ .Values.config.azureTenantId | quote }}
  AZURE_KEYVAULT_URL: {{ .Values.config.azureKeyVaultUrl | quote }}
  AZURE_KEK_NAME: {{ .Values.config.azureKekName | quote }}
  AZURE_KEK_VERSION: {{ .Values.config.azureKekVersion | quote }}
  AZURE_KEYVAULT_SECRET_URL: {{ .Values.config.azureKeyVaultSecretUrl | quote }}

  JWT_AUDIENCE: {{ .Values.config.jwtAudience | quote }}
  JWT_ISSUER: {{ .Values.config.jwtIssuer | quote }}
  JWT_JWKS_URL: {{ .Values.config.jwtJwksUrl | quote }}
